set tabstop=4
set shiftwidth=4
set number
set diffopt+=iwhite
highlight DiffChange ctermbg=0
set expandtab
set hlsearch
set wildmenu
set novisualbell
set noerrorbells
set belloff=all
highlight StatusLineNC cterm=bold ctermfg=white ctermbg=darkgray
set noswapfile
syntax on
set smarttab
set smartindent

let g:netrw_preview   = 1
let g:netrw_liststyle = 3
let g:netrw_winsize   = 70
let g:netrw_altv = 1

nmap <silent> <A-Up> :wincmd k<CR>
nmap <silent> <A-Down> :wincmd j<CR>
nmap <silent> <A-Left> :wincmd h<CR>
nmap <silent> <A-Right> :wincmd l<CR>
nmap <C-Up>    :resize+5<CR>
nmap <C-Down>  :resize-5<CR>
nmap <C-Left>  :vertical resize-5<CR>
nmap <C-Right> :vertical resize+5<CR>

nmap <F3> :grep -r '<cword>' . <cr>
nmap <F4> :wincmd q<CR>
nmap <F5> :wincmd x<CR>

